site_name: Airspecs
site_url: https://airspecs.media.mit.edu
theme: material
repo_url: https://github.com/pchwalek/env_glasses
strict: true

markdown_extensions:
  - smarty
  - sane_lists
  - footnotes
  - codehilite
  - meta

plugins:
  - search

nav:
  - Home: 'index.md'
  - 'software':
    - 'Nix': 'nix.md'
    - 'MkDocs': 'docs.md'
