site_name: Airspecs
site_url: https://airspecs.resenv.org
theme: material
repo_url: https://github.com/pchwalek/env_glasses
edit_uri: https://github.com/mammothbane/airspec/edit/master/src/web/docs/docs
strict: true

markdown_extensions:
  - smarty
  - sane_lists
  - footnotes
  - codehilite
  - meta

plugins:
  - search

nav:
  - home: index.md
  - software:
    - api: software/api.md
    - auth: software/auth.md
    - protobuf: software/proto.md
    - nix: software/nix.md
    - mkDocs: software/docs.md
